apiVersion: v2
publisher: eclipse
name: che-theia
version: next
type: Che Editor
displayName: theia-ide
title: Eclipse Theia development version.
description: Eclipse Theia, get the latest release each day.
icon: https://raw.githubusercontent.com/theia-ide/theia/master/logo/theia-logo-no-text-black.svg?sanitize=true
category: Editor
repository: https://github.com/eclipse/che-theia
firstPublicationDate: "2019-03-07"
spec:
  endpoints:
   -  name: "theia"
      public: true
      targetPort: 3100
      attributes:
        protocol: http
        type: ide
        secure: true
        cookiesAuthEnabled: true
        discoverable: false
   -  name: "webviews"
      public: true
      targetPort: 3100
      attributes:
        protocol: http
        type: webview
        secure: true
        cookiesAuthEnabled: true
        discoverable: false
        unique: true     
   -  name: "che-rsync"
      public: false
      targetPort: 2222
      attributes:
        protocol: TCP
        discoverable: false
  containers:
   - name: theia-ide
     image: "quay.io/eclipse/che-theia:next"
     memoryLimit: "512M"
   - name: che-rsync
     image: "vparfonov/che-rsync:latest"
     lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "/bin/restore.sh"]
      preStop:
        exec:
          command: ["/bin/sh","-c","/bin/backup.sh"] 
     mountSources: true
     ports:
         - exposedPort: 2222
     memoryLimit: "1Gi"    
  initContainers:
  - name: remote-runtime-injector
    image: "eclipse/che-theia-endpoint-runtime-binary:next"
    volumes:
      - mountPath: "/remote-endpoint"
        name: remote-endpoint
        ephemeral: true
    env:
      - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
        value: /remote-endpoint/plugin-remote-endpoint
      - name: REMOTE_ENDPOINT_VOLUME_NAME
        value: remote-endpoint
